### ISSUE TITLE
Crash: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by esk33** [John200410/rusherhack-spotify#2]
When setting up the Spotify plugin on Linux, the plugin shows up in the HUD editor ok but when I try to click "Authenticate" the game crashes with a "The BROWSE action is not supported on the current platform!" error.

Is there a way to authenticate Spotify without it trying to open the browser?

Crash report: https://mclo.gs/DMaBTzg
System: Arch Linux
Launcher: MultiMC
Mods: Rusherhack, Baritone, ViaFabricPlus, Meteor Client, Xaero's Minimap, Xaero's World Map, Xaero's Minimap Plus

**Comment by John200410** [comment]
Hello,

You can manually go to the web page in your browser: http://localhost:4000/

**Comment by John200410** [comment]
Fixed in recent commit

**Comment by esk33** [comment]
Thank you!
